(dp1
S'output'
p2
S"<type 'exceptions.TypeError'> URL() got an unexpected keyword argument 'client_side'"
p3
sS'layer'
p4
S'/home/ebratt/PycharmProjects/csc503/web2py/applications/csc503/controllers/simulation.py'
p5
sS'code'
p6
S'# -*- coding: utf-8 -*-\nfrom gluon.storage import Storage\n\nresponse.files.append(URL(\'static\', \'css/prettify.css\'))\nresponse.files.append(URL(\'static\', \'js/prettify.js\'))\n\n@auth.requires_login()\ndef index():\n    docs = Storage()\n    docs.simulation = """\n#### Select an algorithm and the input data. psim2web2py will submit a task to the web2py Scheduler. For example,\n``\nscheduler.queue_task(floating_point_add, task_name=\'floating_point_add\')\n``:python\n\nInstructions:\n - Select the **Algorithm**\n - Select the **Input Data** (must be compatible with the algorithm)\n - Hit **Submit** (this will persist the data to the db)\n - Hit **Calculate** (this queues a task for the scheduler)\n - You will be re-directed to the Monitor and can view the status of the task\n - Wait a few seconds or hit Auto-Refresh\n\nWhat you should see in the monitoring dashboard:\n - One worker is **ACTIVE**\n - One scheduler_task gets **QUEUED**, goes into **ASSIGNED**, then **RUNNING**, and then becomes **COMPLETED**\n - When the task is **RUNNING**, a scheduler_run record pops up (**RUNNING**)\n - When the task is **COMPLETED**, the scheduler_run record is updated to show a **COMPLETED** or **FAILED** or\n   **TIMEOUT** status (the default timeout is 60 seconds).\n    """\n\n    form = SQLFORM(db.simulation,\n                   fields=[\'algorithm\', \'input_data\'],\n                   submit_button=\'Calculate\')\n    simulation_id = None\n    algorithm = None\n    # if form.process(keepvalues=True).accepted:\n    if form.validate():\n        algorithm_id = int(form.vars.algorithm)\n        input_id = int(form.vars.input_data)\n        query = db(db.input_data.algorithms.contains(algorithm_id)).select()\n        valid_input = [item.id for item in query]\n        def input_is_valid():\n            result = False\n            for x in valid_input:\n                if x == input_id:\n                    result = True\n                    break\n            return result\n        if input_is_valid():\n            algorithm = db(db.algorithm.id==algorithm_id).select()[0].Name\n            form.vars.id = db.simulation.insert(**dict(form.vars))\n            session.flash = \'Simulation created\'\n            redirect(URL(\'manage\', \'worker1\',\n                         args=[simulation_id, algorithm],\n                         client_side=True))\n        else:\n            response.flash = \'Invalid input data!\'\n    elif form.errors:\n        response.flash = \'form has errors\'\n    else:\n        response.flash = \'please fill out the form\'\n\n    return dict(docs=docs, form=form, simulation_id=simulation_id, algorithm=algorithm)\n\n\nresponse._vars=response._caller(index)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/ebratt/PycharmProjects/csc503/web2py/gluon/restricted.py", line 224, in restricted\n    exec ccode in environment\n  File "/home/ebratt/PycharmProjects/csc503/web2py/applications/csc503/controllers/simulation.py", line 67, in <module>\n  File "/home/ebratt/PycharmProjects/csc503/web2py/gluon/globals.py", line 393, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/ebratt/PycharmProjects/csc503/web2py/gluon/tools.py", line 3444, in f\n    return action(*a, **b)\n  File "/home/ebratt/PycharmProjects/csc503/web2py/applications/csc503/controllers/simulation.py", line 56, in index\n    client_side=True))\nTypeError: URL() got an unexpected keyword argument \'client_side\'\n'
p11
s.